### ISSUE TITLE
Documentation - Howto reboot device after loading micropython.zip?

### ISSUE THREAD

**Issue by tdaileygithub** [daniel-thompson/wasp-os#12]
Great Work!  Very cool way of interacting with pinetime.

- How do you reboot the device after uploading micropython.zip?
   - I can connect to the UART service using wasptool but I can't figure out how to reset the device without going back to openocd.  I was guessing a long button press?

- What is your workflow for making changes to the python scripts on the watch?  
-- How do you edit the python files on device or do you simply reset [see above?] and upload a new zip?

**Comment by tdaileygithub** [comment]
"How to develop wasp-os python applications on a Pine64 PineTime"

`https://www.youtube.com/watch?v=kf1VHj587Mc`

Exactly right!  
Maybe add link in Readme.md

**Comment by daniel-thompson** [comment]
Thanks for the update. Great to know that the video is useful!

PS There is already a link to it in the readme... IIRC it was added the same day I published the video.
