### ISSUE TITLE
Questions about the future of wasp-os

### ISSUE THREAD

**Issue by Izaic** [daniel-thompson/wasp-os#122]
Hey Daniel,

I am curious what your vision is for Wasp-OS once 0.4 is released and it's considered "Mature"? And will future features of Wasp-OS be compatible with the Pinetime? Or will you expand it beyond the Pinetime's limitations and leave the Pinetime behind in terms of what it can do? I hear the ram situation is getting pretty dire, so I'm curious about it's outlook beyond release 0.4 and maybe some minor improvements.

Do you think there's more optimizations that could be done possibly with a newer micropython for example so that more could be squeezed in and also allow for things such as bluetooth pairing with gadgetbridge finally? And on the note of newer libraries and bases, will the depreciated gatttools be phased out so that it's easier for people to setup a Wasp-OS dev environment?

**Comment by Kozova1** [comment]
It might be also possible to load some apps on demand, maybe the games or some less used apps.

This might help save some ram, instead of registering everything immediately into the launcher.
