### ISSUE TITLE
Step Counter not working

### ISSUE THREAD

**Issue by SecureCodeJIT** [daniel-thompson/wasp-os#125]
updated sealed unit everything else works.  steps counter does not update.

**Comment by daniel-thompson** [comment]
Which watch model?

**Comment by SecureCodeJIT** [comment]
Last night steps started working don't understand the delay.  not sure model bought a couple of months ago.

**Comment by daniel-thompson** [comment]
Surely you know what type of watch you actually bought though?
https://wasp-os.readthedocs.io/en/latest/install.html#device-support

**Comment by pkubaj** [comment]
I have a PineTIme (sealed) and I think I can confirm this issue.

Right after flashing WaspOS (tag 0.3), I walked into another room and the step counter showed some steps, but then stopped updating when I walked around the house.

The next day, however, it worked fine and seems to work fine now (it's the day after now).
