### ISSUE TITLE
Help for use wasp simulator with Twatch 2020

### ISSUE THREAD

**Issue by picpic020960** [daniel-thompson/wasp-os#130]
Hello Sactre and Daniel
sorry for my bad english (French)
wasp firmware for Twatch 2020 ok on my watch.
How to use the simulator for some update in python firmware ( Timer , Alarm)
I tested a few things but now I'm lost
Thanks for help

https://github.com/sactre/wasp-os

_Originally posted by @picpic020960 in https://github.com/daniel-thompson/wasp-os/issues/58#issuecomment-748448117_

**Comment by daniel-thompson** [comment]
I'm afraid I don't understand. I'm get how the wasp simulator could be used on a Twatch 2020.

**Comment by picpic020960** [comment]
Thanks for reply
this repo is for example : https://github.com/sactre/wasp-os
Twatch 2020 + wasp-os (fork) 
maybe someone else will have some ideas
Regards

**Comment by daniel-thompson** [comment]
> maybe someone else will have some ideas

Maybe.

What the actually question is remains very unclear!

The wasp-os simulator is one type of (simulated) device and and the Twatch 2020 is a completely different device. You cannot do Twatch 2020 development using the simulator. What is the link between them?

**Comment by picpic020960** [comment]
Twatch 2020 is ESP32 with micropython. 
see this example https://github.com/sactre/wasp-os : Twatch 2020/ESP32 with wasp-os
but without simulator. it's why my question.
Twatch  hardware is better than Pinetime...

**Comment by daniel-thompson** [comment]
To be honest I'm still clear what the questons is since there is no link between the simulator and the Twatch 2020 ports. Howeverit might be better to raise this on sactre's fork anyway so I'm going to close this at this point.
