### ISSUE TITLE
pygobject and pydbus module are required for wasptool 'rtc' option

### ISSUE THREAD

**Issue by pstarliu** [daniel-thompson/wasp-os#159]
Hi

I am following the document for flashing wasp-os into my pinetime, and it works the first time. 

But to set the initial time, both wasptool 'console' option and 'rtc' options doesn't working for me. I am not a python developer, but inspecting the error log that my guessing is 'pydbus' and 'pygobject' modules missing, and after install both, the command 'wasptool --rtc' successful set the correct local time. 

I am using a Pinebook pro with the preinstalled Manjaro Linux.

**Comment by pstarliu** [comment]
Hi @daniel-thompson, why it the issue been closed?

**Comment by daniel-thompson** [comment]
github closes issues automatically when a fix committed.

**Comment by pstarliu** [comment]
Cool, now I saw the linked Commit id, thanks @daniel-thompson
