### ISSUE TITLE
Unable to connect to gadget bridge

### ISSUE THREAD

**Issue by shuhaowu** [daniel-thompson/wasp-os#162]
I just built wasp-os on master and flashed it onto the pinetime. I'm unable to find it in Gadget bridge. I can see it in nrf  connect, but I only see a Nordic UART service and two Generic attribute (uuid 1800 and 1801). Are features like the time service, notification, and what not simply not implemented, or am I doing something wrong?

If these are not implemented, are there any pointers on how I can try to address these issues?

**Comment by Kozova1** [comment]
Are you using the [custom gadgetbridge fork](https://github.com/daniel-thompson/gadgetbridge)?

**Comment by shuhaowu** [comment]
I am not. I see [upstream is looking to resolve some conflicts](https://codeberg.org/daniel-thompson/Gadgetbridge/pulls/1). Does anyone own this work? If not, I can try my hands rebasing that change and sending it upstream.

**Comment by Kozova1** [comment]
Upstream has merged wasp-os, now we either need to wait for a new release or build from source.

**Comment by Kozova1** [comment]
@shuhaowu Gadgetbridge just released a new version that supports wasp-os out of the box - 0.53
