### ISSUE TITLE
OverflowError when using one of the 'spinner'-widgets in the 'Date'-settings on the PineTime

### ISSUE THREAD

**Issue by christopherpeters-git** [daniel-thompson/wasp-os#167]
Steps to reproduce:
1. Open 'settings' app
2. Swipe to 'Date'
3. Tap two times on one of the spinners

After the display of the exception a chain of other exceptions of the same type occure and i can only restart it to use it again.

The error is raised by 'time.localtime(...)' in 'get_localtime()' in apps/nrf_rtc.py. 'time.localtime(...) seems to raise the error when the input is greater than or equals 1 << 31, like a guy states in the [micropython forum](https://forum.micropython.org/viewtopic.php?t=8486)

I cant reproduce this in the simulator.

**Comment by christopherpeters-git** [comment]
May i ask, why this issue was closed? This was my first issue i ever created in foreign project, so i would like to know what the reason is. @daniel-thompson

**Comment by daniel-thompson** [comment]
github automatically closes issues when they are fixed. Follow the link in "closed this" message above!

**Comment by christopherpeters-git** [comment]
sorry, didnt knew that! Thank you for the fix
