### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by jaakaappi** [daniel-thompson/wasp-os#17]
Hi, I really like what you are doing and plan to do something with PineTime and wasp-os once I have time from my exams. In the meantime, is there a way I could throw a couple of bucks at you, e.g. via PayPal or Github Sponsors?

Keep up the good work :+1:

**Comment by daniel-thompson** [comment]
I hope you enjoy playing with PineTime. I am!

Regarding donations for wasp-os, it's very kind but let's put those bucks in a charity bucket somewhere. Right now I'm sitting next to a guitar that I inherited when my uncle died and that makes cancer research charities a good option from my point of view.
