### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptography'

### ISSUE THREAD

**Issue by bmsleight** [daniel-thompson/wasp-os#170]
PR to follow

bms@DrStone:~/wasp-os$ make -j `nproc` BOARD=pinetime all
rm -f bootloader/_build-pinetime_nrf52832//pinetime_nrf52832_bootloader-*-nosd.hex
make -C micropython/mpy-cross
make -C bootloader/ BOARD=pinetime_nrf52832 all genhex
make[1]: Entering directory '/home/bms/wasp-os/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make[1]: Entering directory '/home/bms/wasp-os/bootloader'
GEN build/genhdr/mpversion.h
CC main.c
LD pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.out
LINK mpy-cross

CR pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.hex
   text	   data	    bss	    dec	    hex	filename
  22856	    152	  19970	  42978	   a7e2	_build-pinetime_nrf52832/pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.out

make[1]: Leaving directory '/home/bms/wasp-os/bootloader'
python3 tools/hexmerge.py \
	bootloader/_build-pinetime_nrf52832/pinetime_nrf52832_bootloader-*-nosd.hex \
	bootloader/lib/softdevice/s132_nrf52_6.1.1/s132_nrf52_6.1.1_softdevice.hex \
	-o build-pinetime/bootloader.hex
   text	   data	    bss	    dec	    hex	filename
 287875	  17104	    904	 305883	  4aadb	mpy-cross
make[1]: Leaving directory '/home/bms/wasp-os/micropython/mpy-cross'
rm -f micropython/ports/nrf/build-pinetime-s132/frozen_content.c
make -C micropython/ports/nrf \
	BOARD=pinetime SD=s132 \
	MICROPY_VFS_LFS2=1 \
	FROZEN_MANIFEST=/home/bms/wasp-os/wasp/boards/pinetime/manifest.py \
	USER_C_MODULES=/home/bms/wasp-os/wasp/modules
make[1]: Entering directory '/home/bms/wasp-os/micropython/ports/nrf'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Including User C Module from /home/bms/wasp-os/wasp/modules/bma42x-upy
python3 tools/hex2c.py build-pinetime/bootloader.hex > \
	reloader/src/boards/pinetime/bootloader.h
GEN build-pinetime-s132/genhdr/mpversion.h
CC modules/uos/moduos.c
CC ../../lib/utils/pyexec.c
MPY apps/word_clock.py
python3 -m nordicsemi dfu genpkg \
	--bootloader bootloader/_build-pinetime_nrf52832//pinetime_nrf52832_bootloader-*-nosd.hex \
	--softdevice bootloader/lib/softdevice/s132_nrf52_6.1.1/s132_nrf52_6.1.1_softdevice.hex \
	build-pinetime/bootloader-daflasher.zip
GEN build-pinetime-s132/frozen_content.c
CC build-pinetime-s132/frozen_content.c
Zip created at build-pinetime/bootloader-daflasher.zip
make -C reloader/ BOARD=pinetime
make[1]: Entering directory '/home/bms/wasp-os/reloader'
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader.elf
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa_mcuboot.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader-mcuboot.elf
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/factoryflash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader-factory.elf
LINK build-pinetime-s132/firmware.elf
arm-none-eabi-objcopy -O ihex build-pinetime/reloader.elf build-pinetime/reloader.hex
arm-none-eabi-objcopy -O binary build-pinetime/reloader-mcuboot.elf build-pinetime/reloader-mcuboot.bin.tmp
lib/mcuboot/scripts/imgtool.py create \
	--align 4 --version 1.0.0 \
	--header-size 32 --slot-size 475136 --pad-header build-pinetime/reloader-mcuboot.bin.tmp build-pinetime/reloader-mcuboot.bin
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader.hex build-pinetime/reloader.zip
arm-none-eabi-objcopy -O ihex build-pinetime/reloader-factory.elf build-pinetime/reloader-factory.hex
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader-factory.hex build-pinetime/reloader-factory.zip
Traceback (most recent call last):
  File "/home/bms/wasp-os/reloader/lib/mcuboot/scripts/imgtool.py", line 17, in <module>
    from imgtool import main
  File "/home/bms/wasp-os/reloader/lib/mcuboot/scripts/imgtool/main.py", line 21, in <module>
    import imgtool.keys as keys
  File "/home/bms/wasp-os/reloader/lib/mcuboot/scripts/imgtool/keys/__init__.py", line 19, in <module>
    from cryptography.hazmat.backends import default_backend
ModuleNotFoundError: No module named 'cryptography'
make[1]: *** [Makefile:56: build-pinetime/reloader-mcuboot.bin] Error 1
make[1]: *** Waiting for unfinished jobs....
Zip created at build-pinetime/reloader.zip
Zip created at build-pinetime/reloader-factory.zip
make[1]: Leaving directory '/home/bms/wasp-os/reloader'
make: *** [Makefile:51: reloader] Error 2
make: *** Waiting for unfinished jobs....
   text	   data	    bss	    dec	    hex	filename
 303160	    180	   1836	 305176	  4a818	build-pinetime-s132/firmware.elf
arm-none-eabi-objcopy -O binary build-pinetime-s132/firmware.elf build-pinetime-s132/firmware.bin
arm-none-eabi-objcopy -O ihex build-pinetime-s132/firmware.elf build-pinetime-s132/firmware.hex
make[1]: Leaving directory '/home/bms/wasp-os/micropython/ports/nrf'
python3 -m nordicsemi dfu genpkg \
	--dev-type 0x0052 \
	--application micropython/ports/nrf/build-pinetime-s132/firmware.hex \
	build-pinetime/micropython.zip
Zip created at build-pinetime/micropython.zip
bms@DrStone:~/wasp-os$ pip3 install --user cryptography
Collecting cryptography
  Downloading cryptography-3.4.6-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 452 kB/s 
Collecting cffi>=1.12
  Downloading cffi-1.14.5-cp39-cp39-manylinux1_x86_64.whl (406 kB)
     |████████████████████████████████| 406 kB 1.4 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 1.5 MB/s 
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.14.5 cryptography-3.4.6 pycparser-2.20
bms@DrStone:~/wasp-os$ make -j `nproc` BOARD=pinetime all
rm -f bootloader/_build-pinetime_nrf52832//pinetime_nrf52832_bootloader-*-nosd.hex
make -C micropython/mpy-cross
make[1]: Entering directory '/home/bms/wasp-os/micropython/mpy-cross'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make -C bootloader/ BOARD=pinetime_nrf52832 all genhex
make[1]: Entering directory '/home/bms/wasp-os/bootloader'
make[1]: Leaving directory '/home/bms/wasp-os/micropython/mpy-cross'
rm -f micropython/ports/nrf/build-pinetime-s132/frozen_content.c
make -C micropython/ports/nrf \
	BOARD=pinetime SD=s132 \
	MICROPY_VFS_LFS2=1 \
	FROZEN_MANIFEST=/home/bms/wasp-os/wasp/boards/pinetime/manifest.py \
	USER_C_MODULES=/home/bms/wasp-os/wasp/modules
make[1]: Entering directory '/home/bms/wasp-os/micropython/ports/nrf'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Including User C Module from /home/bms/wasp-os/wasp/modules/bma42x-upy
LD pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.out

CR pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.hex
   text	   data	    bss	    dec	    hex	filename
  22856	    152	  19970	  42978	   a7e2	_build-pinetime_nrf52832/pinetime_nrf52832_bootloader-0.3.0-38-g1d128f1-nosd.out

make[1]: Leaving directory '/home/bms/wasp-os/bootloader'
python3 tools/hexmerge.py \
	bootloader/_build-pinetime_nrf52832/pinetime_nrf52832_bootloader-*-nosd.hex \
	bootloader/lib/softdevice/s132_nrf52_6.1.1/s132_nrf52_6.1.1_softdevice.hex \
	-o build-pinetime/bootloader.hex
python3 tools/hex2c.py build-pinetime/bootloader.hex > \
	reloader/src/boards/pinetime/bootloader.h
python3 -m nordicsemi dfu genpkg \
	--bootloader bootloader/_build-pinetime_nrf52832//pinetime_nrf52832_bootloader-*-nosd.hex \
	--softdevice bootloader/lib/softdevice/s132_nrf52_6.1.1/s132_nrf52_6.1.1_softdevice.hex \
	build-pinetime/bootloader-daflasher.zip
GEN build-pinetime-s132/frozen_content.c
CC build-pinetime-s132/frozen_content.c
LINK build-pinetime-s132/firmware.elf
Zip created at build-pinetime/bootloader-daflasher.zip
make -C reloader/ BOARD=pinetime
make[1]: Entering directory '/home/bms/wasp-os/reloader'
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader.elf
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa_mcuboot.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/flash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader-mcuboot.elf
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -g3 -Os -ffunction-sections -fdata-sections -DNRF52832_XXAA -Ilib/CMSIS/CMSIS/Core/Include -Ilib/nrfx -Ilib/nrfx/drivers/include -Ilib/nrfx/mdk -Ilib/nrfx/hal -Isrc/boards/pinetime -Isrc -Wl,-Map=build-pinetime/reloader.map -Lsrc -Llib/nrfx/mdk -Tnrf52832_xxaa.ld build-pinetime/main.o build-pinetime/blit.o build-pinetime/factoryflash.o build-pinetime/spi.o build-pinetime/spinor.o build-pinetime/st7789.o build-pinetime/wdt.o build-pinetime/nrfx_nvmc.o build-pinetime/gcc_startup_nrf52.o build-pinetime/system_nrf52.o -o build-pinetime/reloader-factory.elf
arm-none-eabi-objcopy -O binary build-pinetime/reloader-mcuboot.elf build-pinetime/reloader-mcuboot.bin.tmp
arm-none-eabi-objcopy -O ihex build-pinetime/reloader.elf build-pinetime/reloader.hex
lib/mcuboot/scripts/imgtool.py create \
	--align 4 --version 1.0.0 \
	--header-size 32 --slot-size 475136 --pad-header build-pinetime/reloader-mcuboot.bin.tmp build-pinetime/reloader-mcuboot.bin
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader.hex build-pinetime/reloader.zip
arm-none-eabi-objcopy -O ihex build-pinetime/reloader-factory.elf build-pinetime/reloader-factory.hex
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader-factory.hex build-pinetime/reloader-factory.zip
rm -f build-pinetime/reloader-mcuboot.bin.tmp
python3 -m nordicsemi dfu genpkg --dev-type 0x0052 --application build-pinetime/reloader-mcuboot.bin build-pinetime/reloader-mcuboot.zip
Zip created at build-pinetime/reloader.zip
Zip created at build-pinetime/reloader-mcuboot.zip
Zip created at build-pinetime/reloader-factory.zip
make[1]: Leaving directory '/home/bms/wasp-os/reloader'
cp reloader/build-pinetime/reloader*.zip build-pinetime
   text	   data	    bss	    dec	    hex	filename
 303160	    180	   1836	 305176	  4a818	build-pinetime-s132/firmware.elf
arm-none-eabi-objcopy -O binary build-pinetime-s132/firmware.elf build-pinetime-s132/firmware.bin
arm-none-eabi-objcopy -O ihex build-pinetime-s132/firmware.elf build-pinetime-s132/firmware.hex
make[1]: Leaving directory '/home/bms/wasp-os/micropython/ports/nrf'
python3 -m nordicsemi dfu genpkg \
	--dev-type 0x0052 \
	--application micropython/ports/nrf/build-pinetime-s132/firmware.hex \
	build-pinetime/micropython.zip
Zip created at build-pinetime/micropython.zip
bms@DrStone:~/wasp-os$

**Comment by daniel-thompson** [comment]
Replaced by PR.
