### ISSUE TITLE
Dice Roll App

### ISSUE THREAD

**Issue by FlameKat53** [daniel-thompson/wasp-os#173]
here's my idea for a dice app, i hope it actually works on real hardware. please test when you (any tester) have the time.

[dice.zip](https://github.com/daniel-thompson/wasp-os/files/6080386/dice.zip)
based on the clock app

**Comment by daniel-thompson** [comment]
Sounds like an interesting idea but please could you share the code as a pull request rather then via the issue tracker?

**Comment by FlameKat53** [comment]
will do

**Comment by FlameKat53** [comment]
I have also added a coin flip app in the dice app, I named the two "Flip Roll"
