### ISSUE TITLE
Touch screen not working on some P8 devices

### ISSUE THREAD

**Issue by ildar** [daniel-thompson/wasp-os#176]
I installed the FW on my P8 and found that touch doesn't respond. It probably has another touch IC. There's a video on that topic: https://youtu.be/jgjKaSETY8Y
ATCwatch FW worked. So I guess that this would help: https://github.com/atc1441/ATCwatch/commit/7f693d9ebed80acf56723eff75c51ac648d7829e

**Comment by daniel-thompson** [comment]
wasp-os is already tested on both known versions of the touch screen device (and does not use the X/Y data on swipe so it does not need a fix like the one seen in ATCwatch).

**Comment by pebri86** [comment]
Maybe something wrong when ts chip initialization, it happen once to my P8. Let the battery drain out then it will work.

**Comment by ildar** [comment]
100% right. Power drain cycle helped.
