### ISSUE TITLE
Debug with JLinkRTTViewer

### ISSUE THREAD

**Issue by kung1388** [daniel-thompson/wasp-os#183]
How to modify the code for debug with JLinkRTTViewer?

**Comment by daniel-thompson** [comment]
I think you would be better off discussing this on the MicroPython forums. The  code to integrate with RTT will be the same for all boards.

**Comment by ildar** [comment]
I just opened a separate issue for the BL: https://github.com/daniel-thompson/wasp-os/issues/196
