### ISSUE TITLE
reloader-factory.zip in 0.4 doesn't work but from 0.3 it does

### ISSUE THREAD

**Issue by koileLab** [daniel-thompson/wasp-os#202]
Hey Thanks for your Work and the detailed documentation!

I exprienced going back to infiniTime that the reloader-factory.zip from the 0.4 Release didn't work via nRF Connect on LineageOS 18.1 (Android 11) it's 211kB large. It just crashed without notification in higher % Area.. 

The 310kB large reloader-factory.zip from 0.3 does work and leads me to InfiniTime 0.9.0.

The was also expirienced by someone else on PineTime Matrix/Discord Chanel...

**Comment by daniel-thompson** [comment]
This was a mistake generating the 0.4 tarball (it acidentally picked up some prototype work to support the newer bootloader). I have built it again and it is working correctly now.

I've also checked in the code to work with the mcuboot (v1.0.0) and infinitime-lite. I've had it pended for release for a long time but I didn't notice that the new firmware had been approved for sealed watch builds. Anyhow it can be picked up from https://github.com/daniel-thompson/wasp-os/actions?query=is%3Asuccess+branch%3Amaster+workflow%3Abinary
