### ISSUE TITLE
Expertise needed to extract pinetime raw heartrate data, as seen in one of the wasp-os videos

### ISSUE THREAD

**Issue by limoncelli** [daniel-thompson/wasp-os#204]
Peter and I would like to have your view on the following siglo [issue](https://github.com/alexr4535/siglo/issues/33).

The basic idea is to get raw data from the sensor and pair it with the actual heartrate (however one is measuring, even manually). This data could be used to train a tensorflow model, which may help to have less jumping of the heartrate values. So we were wondering what you showed in your video when using the wasp-os heartrate app, and if this data would be somehow extractable, either as a stream to siglo or as a download from the watch's memory after 60secs of measurement.

Many thanks!

**Comment by daniel-thompson** [comment]
Firstly be aware that the signal displayed in the video is not the raw data. There's practically no way to graph the raw data on the tiny PineTime screen and even if you could graph it can be nearly unreadable without a bit of DSP to clean it up.

Anyhow, by coincidence I was already working to add the [capability to capture the raw data](https://forum.pine64.org/showthread.php?tid=13727&pid=93629#pid93629).

Anyhow I checked it in this evening. Implementation is [here](https://github.com/daniel-thompson/wasp-os/commit/92812e5ad255452535c0d95e4427df443d2ec134), CI binaries are [here](https://github.com/daniel-thompson/wasp-os/actions/runs/814634226) and documentation is [here](https://wasp-os.readthedocs.io/en/latest/apps.html#heart-rate-monitor).
