### ISSUE TITLE
Unregistering apps doesn't remove the module containing the app code, just the single instance of the application.

### ISSUE THREAD

**Issue by Liorst4** [daniel-thompson/wasp-os#214]
Steps to re-create:

1. Reboot the watch
2. Connect to console
3. from the console
```python
>>> import sys
>>> sys.modules
```
4. Go to the software app and mark 2048
5. from the console
```python
>>> sys.modules
>>> wasp,gc.mem_free()
```
2048 will be there.
6. Go to software app and uncheck 2048
7. from the console 
```python
>>> sys.modules
>>> wasp.gc.mem_free()
````
2048 will still be there and the GC didn't collect the assets from the 2048 module.

**Comment by Liorst4** [comment]
https://github.com/daniel-thompson/wasp-os/commit/e76a4afd8550145d4c43b3f1513b2fd209af8dd1 Reloads the application, but `unregister` still doesn't delete the module, just the app instance.

**Comment by daniel-thompson** [comment]
Thanks for the original report BTW. GitHub is a little abrupt when it auto-closes issues like this!
  

  
>  e76a4af Reloads the application, but
  
>  unregister still doesn't delete the module, just
  
>  the app instance.
  

  
There is no new code in the unregister because we can drop the references to the module from the register() function instead.
  

  

  
  
  
  
>

**Comment by Liorst4** [comment]
> There is no new code in the unregister because we can drop the references to the module from the register() function instead.

Yup, realized it after I wrote the comment :P
Thought that deleting the comment will spare you the notification.

> Thanks for the original report BTW

Glad to help! :smile:
