### ISSUE TITLE
Cannot import name 'Serial' from 'serial' on Raspberry Pi

### ISSUE THREAD

**Issue by Pittconnect** [daniel-thompson/wasp-os#216]
![image](https://user-images.githubusercontent.com/30482556/121448981-c8f0bf00-c966-11eb-9892-2fab8025985e.png)

I have two python installed 2.7 and 3.7 It did pick the right python that is 3.7 prior to running git fetch origin command. Now it wants to pick 2.7 not sure why the error message.  Wasp-os does require python 3.6 or higher was there a roll back to support 2.7 ?

**Comment by daniel-thompson** [comment]
Looks like your pyserial installation Is damaged. Why is there no Serial in your copy of /home/pi/.local/python3.7/site-packages/serial/__init__.py ? Perhaps uninstalling and reinstalling it could help.

**Comment by Pittconnect** [comment]
I did try that and here is the video Did I miss anything ? https://www.youtube.com/watch?v=oN4jNTBleLY

**Comment by Pittconnect** [comment]
Maybe I can manually copy serial but if I knew which one and where that would be helpful.

![image](https://user-images.githubusercontent.com/30482556/121574096-ed46ad00-c9f3-11eb-8c4a-183ea3811adb.png)

**Comment by daniel-thompson** [comment]
The click module is included in the build instructions: https://wasp-os.readthedocs.io/en/latest/install.html#install-prerequisites

What technique did you use to install the click module?

**Comment by Pittconnect** [comment]
Ok I did the pre-installed for wasp-os again as python3 was removed.  And I am back to the the message cannot import serial
Here is the video https://www.youtube.com/watch?v=YpQ4_siN8Cg for details And I am not using docker should I be using docker ?

**Comment by daniel-thompson** [comment]
Please can you share copy 'n paste from the terminal emulator. I can't keep track of things in video form?

**Comment by Pittconnect** [comment]
I believe it may be something to do with user / system permission and how the file are arranged on the system.
Here is the paste version of it. https://pastebin.pl/view/f05aa461  Notice How I get micropython Error 2 when I use sudo command to make the firmware and when I use the local user to make the firmware I get Error 1 and the 3rd I have displayed the content of init.py

**Comment by Pittconnect** [comment]
OK I found the work around https://stackoverflow.com/questions/65788196/cannot-import-name-serial-from-serial
