### ISSUE TITLE
Profile build of wasp-bootloader

### ISSUE THREAD

**Issue by shermozle** [daniel-thompson/wasp-os#229]
Installation doc says:

> Copy reloader-mcuboot.zip (see Building wasp-os from source) to your Android device and download nRF Connect for Android if you do not already have it.

To enable a quick and easy try out of the OS, it'd be great to include a built version of this. Otherwise you have to go through the quite onerous process of installing all the prerequisites (the ARM GCC bits are particularly involved) and compiling it all.

**Comment by daniel-thompson** [comment]
Scroll down ;-). The section immediately after the instructions on build from source describe exactly this: https://wasp-os.readthedocs.io/en/latest/install.html#binary-downloads

**Comment by shermozle** [comment]
Where is reloader-mcuboot.zip?

**Comment by Itai-Nelken** [comment]
In the tar.gz archive in the release
