### ISSUE TITLE
wasp.watch.drawable.wrap() breaks short lines containing spaces

### ISSUE THREAD

**Issue by fgaz** [daniel-thompson/wasp-os#230]
```
>>> wasp.watch.drawable.wrap("a b",240)
[0, 2, 3]
```

I'd expect it to return `[0, 3]` (like `wrap("abc")`), since it will fit in 240 pixels

**Comment by Pittconnect** [comment]
>>> wasp.watch.drawable.wrap("a,0",240)
[0, 3]
you need to put a place holder to get [0, 3] as output for your wrap command

**Comment by fgaz** [comment]
@Pittconnect with the current behavior yes, but why should "a b" be split if it doesn't exceed 240 characters? Word wrapping usually doesn't turn _every_ space into a newline

> you need to put a place holder to get [0, 3] as output for your wrap command

 is there a placeholder that is guaranteed to have the same width as a space?

**Comment by Pittconnect** [comment]
I am not sure what your questions is ? Or what kind of solution you are looking for ? I just responded to your post base on what you posted was `I'd expect it to return [0, 3]` If you wish to engage in intellectual debate please post your request in a group https://t.me/pinetime, The github issue is to track bugs you find related to wasp-os usage This is not a bug, You split ab into a b which mean ab is acquired 2 space while a b has acquired 3 space  Here are some more examples 
>>> print(watch.rtc.get_localtime())
(2020, 3, 1, 14, 14, 38, 6, 61)
>>> print("WJS""GPS")
WJSGPS
>>> wasp.watch.drawable.wrap("cd",240)
[0, 2]
>>> wasp.watch.drawable.wrap("c d",240)
[0, 2, 3]
>>> wasp.watch.drawable.wrap("a   b",240)
[0, 4, 5]
>>> wasp.watch.drawable.wrap("a    b",240)
[0, 5, 6]
>>> wasp.watch.drawable.wrap("e",240)
[0, 1]
>>>

**Comment by daniel-thompson** [comment]
> The github issue is to track bugs you find related to wasp-os usage. This is not a bug.

I think this is a bug... or, the very least, seriously counter-intuitive.

The wasp-os wrap() function is used to determine where strings should be broken during multi-line rendering. "a b" easily fits onto a single line but wrap() is placing a line break between the two "words" (in other words it is returning `[0, 2, 3]` when `[0, 3]` seems to be more correct).

The effect also affects other strings such as "a b c" which also fits onto a single line but, once again, wrap() is generating a line break between the final two "words" of the string:
```
>>> # W is a very wide character (usually wider than a space)
>>> wasp.watch.drawable.wrap('aWb', 240)
[0, 3]
>>> wasp.watch.drawable.wrap('a b', 240)
[0, 2, 3]
>>> wasp.watch.drawable.wrap('a b c', 240)
[0, 4, 5]
>>> wasp.watch.drawable.wrap('a b c d', 240)
[0, 6, 7]
```

**Comment by daniel-thompson** [comment]
Should now be fixed. Please try with most recent master branch.

**Comment by fgaz** [comment]
Works great, thanks!
