### ISSUE TITLE
12 hour time format

### ISSUE THREAD

**Issue by Izaic** [daniel-thompson/wasp-os#231]
It would be great to have a 12 hour time format for WaspOS like Infinitime offers

**Comment by daniel-thompson** [comment]
wasp-os is all about making it easy to modify watch behaviour but this has been sitting for many months now without anybody volunteering to make these changes. If it doesn't attract attention as an issue then it probably better handled by an interested party implementing and submitting a pull request.

**Comment by tigercoding56** [comment]
would something like time.strftime("%-I:%M:%S %p") work?

**Comment by fgaz** [comment]
@tigercoding56 looks like strftime is not available in micropython https://docs.micropython.org/en/latest/library/time.html
