### ISSUE TITLE
Step counter doesn't appear on new accelerometer Pinetime

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [daniel-thompson/wasp-os#244]
I can't seem to get the step counter on my new Pinetime, I'm guessing there's no driver for the new accelerometer?

**Comment by EnderNightLord-ChromeBook** [comment]
All good, I'm glad I could get this issue out there.

**Comment by daniel-thompson** [comment]
BMA425 support should now be available in the latest CI builds.

**Comment by EnderNightLord-ChromeBook** [comment]
Thank you!
