### ISSUE TITLE
Micropython run_tests fails as path not found on Dietpi hardware in Pine64

### ISSUE THREAD

**Issue by Pittconnect** [daniel-thompson/wasp-os#252]
I had no problem with Pi3 running Raspberry Pi OS but because of some bad Chinese part the Pi became hot and died This is a known problem since 2013 https://www.raspberrypi.org/forums/viewtopic.php?t=230391 SO I improvised and switch to Pine64 and install Dietpi OS to get a similar environment as before. [https://wasp-os.readthedocs.io/en/latest/install.html#install-prerequisites](url) I installed all the prerequisites no problem. BUT I Cannot run the make command without errors https://pastebin.pl/view/789fc4ba because IT cannot find the path to all the dot h files and when I run the micropython/tests/python3 run_tests.py it fails ALso the bluetooth device Sunxi is unable to scan the adapters  ANY IDEAS On what test i should run to Isolate the problem

`Here is the output that shows error 2 like its a PATH problem it is not I have already added usr/lib to the path https://pastebin.pl/view/d26003a0

**Comment by daniel-thompson** [comment]
Looks like you have not installed the GNU-RM toolchain properly. You have managed to pick up gcc-7.3.1 from somewhere on the path instead of an appropriate version of GNU-RM.
