### ISSUE TITLE
Misconfigured ADC?

### ISSUE THREAD

**Issue by fgaz** [daniel-thompson/wasp-os#254]
I noticed that the issue fixed in https://github.com/JF002/InfiniTime/pull/483 in infinitime might affect wasp-os too, and might explain the weird battery readings I'm getting.

The relevant line in micropython should be:

https://github.com/micropython/micropython/blob/782d5b2e534c96f4668443efe37c0514e8fcfe91/ports/nrf/modules/machine/adc.c#L136

Since the problem is specific to the pinetime's configuration, a longer ACQTIME might not be accepted by upstream though.

I'll start by patching it locally and seeing if it improves my readings.

edit: some readings

mV min is right after rebooting the watch after it turned off for lack of power
mV max is when the watch is fully charged

| us ACQtime | mV min | mV max |
|-|-|-|
| 3 | 3131 | 3960 |
| 40 | 3312 | 4218 |

note: battery.charging() always returns 1 when my watch is connected to the charger, so I just waited a few hours until the reading stabilized to get mV max

**Comment by fgaz** [comment]
After doing a couple of charge cycle, I can say that the new readings make way more sense. The min and max voltages are aligned to what one would expect from a new battery.

The discharge curve I observed with ACQTIME=3 had a sharp drop at the beginning, followed by days of low voltage (this is only by looking at the battery icon, i did no formal tests), while with ACQTIME=40 it matches what I would expect from a lithium battery.

I'll prepare a patch for your fork of micropython.

**Comment by kLabz** [comment]
I'm trying this on my watch because it made sense to me since I almost never see the first ~20% (80-100%) of my battery.
However I'm not sure it's good either; my watch is now at 100% while it doesn't seem like it should be. I'll keep an eye on it all day to see if it makes more sense soon.

**Comment by fgaz** [comment]
That's because the current % algorithm (wasp/drivers/battery.py) assumes 4V is 100%, while with the new measurements it should be 4.2V.
