### ISSUE TITLE
Support for P8 Plus / Y20

### ISSUE THREAD

**Issue by fnordsh** [daniel-thompson/wasp-os#259]
Hi,
I just ordered a Colmi P8, intending to try out Wasp OS on it, but the seller sent me a different watch, which is apparently a "P8 Plus". In the about screen, it says: "Y20 / MOY-GAI3-2.1.0"
So, now I'd like to know: Is this model similar enough to the P8 to be supported by Wasp OS, or is support planned for the future, or do I need to return it?
Thank you!

**Comment by fnordsh** [comment]
Okay, so according to the Colmi website, it does have a different CPU (GR5515 instead of NRF52832), among other differences.
So it's probably best to return it. :-/

**Comment by daniel-thompson** [comment]
Afraid so, yes!
