### ISSUE TITLE
DFU Fails Consistently at 1% Progress

### ISSUE THREAD

**Issue by atomdmac** [daniel-thompson/wasp-os#260]
After uploading the bootloader (i.e. `reloader-mcuboot.zip`) to my PineTime, the watch restarted and showed the blue-to-white pine cone screen.  Once that occurred, I was able to re-connect to the watch from my phone via NRFConnect.  When attempting to upload the application image (ex. `micropython.zip`), NRFConnect shows that the upload begins, stops at 1% progress, then the watch screen flickers and appears to reboot.

This also occurs if I try to revert to the factory bootloader using OTA.

Is my dev kit bricked now?

**Comment by daniel-thompson** [comment]
> Is my dev kit bricked now?

No. If you can get the bluetooth logo to change colour (white to blue) then you just need to get your phone to work with it (or, in the worst case, try with a different phone).

nRF Connect has MBR size and number-of-packets preferences (under Settings -> DFU options) that can get stubborn phones to work nicely. Try fiddling with these. One common trick it to reduce the number of packets...
