### ISSUE TITLE
How Get BLE MAC Address?

### ISSUE THREAD

**Issue by faustolnx** [daniel-thompson/wasp-os#271]
Hi, 
how get the ble mac address?
I want to show it on the display.
Thanks 
Fausto

**Comment by daniel-thompson** [comment]
I don't think there is any python interface for this. You will need to check the Nordic Softdevice SDK to figure out what the API is to look up the MAC and then add some bindings to read this from within python.

The code will end up similar to this code (which added bindings to tell us if BLE was connected or not): https://github.com/daniel-thompson/micropython/commit/f5797fb41555732defd5d375e69f3d33b3aaee02

**Comment by fgaz** [comment]
There is an interface actually!

```python
import ble
address = ble.address()
```

**Comment by daniel-thompson** [comment]
> There is an interface actually!

Excellent. Thanks for setting us straight.

**Comment by faustolnx** [comment]
Hi,
Thanks for your help

**Comment by kLabz** [comment]
> There is an interface actually!
> 
> ```python
> import ble
> address = ble.address()
> ```

Did someone get somewhere from this?

I have a peculiar but working setup, and if I add `import ble` or `from ble import address` I am able to get my ble mac address and run everything fine, _but_ ble connection is broken (can't use wasptool, gadgetbridge, etc.)
