### ISSUE TITLE
BMA421 and HRS3300 on P8B not working

### ISSUE THREAD

**Issue by Elenedeath** [daniel-thompson/wasp-os#290]
hello, i have a senbono P8b (MOY-TON5) working with the p8 board and a cflag commented on another Issue by fanoush.

i can dfu my watch, use apps like calc, alarm. i add some PR like the phone call apps.
but i cant see the stepcounter or the heart monitor working.

Based on the seller where i buy it, i have BMA421 and HRS3300.How i can check it, or debug to see where the problem are?

**Comment by daniel-thompson** [comment]
I doubt a P8b has a BMA421. AFAIK any P8 with magnetic charging does not have a BMA421.

In both cases you can instrument the drivers since I think both drivers try to read version info from the hardware as they initialize.
