### ISSUE TITLE
How to remember phone connected via bluetooth across waspos flash

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [daniel-thompson/wasp-os#341]
Hi,

I very frequently update my wasp os on my pinetime. It's a pain to have to manually resync it to gadget bridge.

Is there currently a way to make the watch remember past device? And if not, is it planned?

Thanks !

**Comment by thiswillbeyourgithub** [comment]
Up @daniel-thompson 

Do you know how it could be possible to access the list of connected device from the watch? I'm so sick of having to reconnect the watch to the phone after every new flashing that I end up never connecting it...

**Comment by daniel-thompson** [comment]
I don't really understand the question. The watch's MAC address is set in the fuses during manufacturing, reflashing it shouldn't have any affect on GadgetBridge's ability to find it.

**Comment by thiswillbeyourgithub** [comment]
I was convinced for some reason that my watch kept failing to connect to my phone after a refresh but I checked and it works fine. Closing this, sorry :)
