### ISSUE TITLE
Release micropython.zip and/or make documentation clearer

### ISSUE THREAD

**Issue by AlwaysLivid** [daniel-thompson/wasp-os#49]
Although the steps (particularly the ones involving DaFlasher) mentioned in the readthedocs.io site seem clear, there's no explanation as to what `micropython.zip` is supposed to be and where to download it, despite the fact that other tools do have download links.

**Comment by daniel-thompson** [comment]
Build instructions are here: https://wasp-os.readthedocs.io/en/latest/README.html#building-from-source

There is not yet a binary release that works with DaFlasher.

**Comment by AlwaysLivid** [comment]
> Build instructions are here: https://wasp-os.readthedocs.io/en/latest/README.html#building-from-source
> 
> There is not yet a binary release that works with DaFlasher.

Understood. I've just been having a couple of issues with the compilers as of lately. Nevertheless, I still believe that it's  not immediately clear that the output of the building process is supposed to be a DFU-flashable ZIP-file called by the aforementioned name.
