### ISSUE TITLE
frontend/backend model for wasp-os apps

### ISSUE THREAD

**Issue by seniorivn** [daniel-thompson/wasp-os#78]
Ideally smartwatch apps should be able to use connected phone apis to do things microcontroller has no ability to do.

 phone companion app could be also a [micro]python apps environment that provides communication between wasp-os apps on the watch and their optional counterparts running in the companion app.

it would make integration with any thirdparty apps/services easy, and variety of possible smartwatch apps much larger

**Comment by daniel-thompson** [comment]
Currently there is only one companion app protocol implemented (the GadgetBridge protocol shared with espruino). It doesn't really have a front end/back end model.

I'm reluctant to design this up front. Better to wait until somebody starts working on a different companion app.
