### ISSUE TITLE
Can't start app by pressing button in bootloader

### ISSUE THREAD

**Issue by SteveAmor** [daniel-thompson/wasp-os#8]
Much as I try pressing the button, if I go into the bootloader, I have to wait for 5 mins for it to time out and start the app.  It does start the app quickly when charging a flat battery (briefly showing the bootloader splash).

**Comment by daniel-thompson** [comment]
The code to read the button is essentially the same in both bootloader and when the main application starts (both just read the value from the hardware every so often).

Hard to say what might be going on.

I guess you could share a video so we can see exactly what is happening but is very strange that the button should work in the application but not in the bootloader.

**Comment by SteveAmor** [comment]
I'm closing this as I just tested it again at it is working.
