### ISSUE TITLE
sdl2.ext.common.SDLError: b'No available video device' (prev: Trouble using "make" term)

### ISSUE THREAD

**Issue by SC-Teuton** [daniel-thompson/wasp-os#84]
I am attempting to install wasp-os however, each step I arrive at that involves the 'make' term flag up this error and I am unsure as to what I have done incorrectly:
![image](https://user-images.githubusercontent.com/56845330/96643414-6edfb280-131f-11eb-9a39-d445f67b4f7e.png)

This screenshot was after another fresh install (as can be seen)

Help would be much appreciated as I look forward to using wasp-os!

**Comment by SteveAmor** [comment]
Hi @SC-Teuton, the install instructions are for Linux and make is not available in Windows. However if you have Windows 10 with WSL, you can follow the instructions here:
https://stackoverflow.com/a/54133058

**Comment by SC-Teuton** [comment]
I apologise to come back with another question with another probably very simple answer.
I have followed the steps to install wasp-os as have been linked above, I installed the ARM Toolchain through the answer in this link: https://unix.stackexchange.com/a/377350 since I'm on windows 64-bit and the website linked in the installation guide only supports 32-bit.

Everything, up to this point, has seemingly worked well or has been fixed by research. The main problem I am facing now is this with the 'make sim' command. I get the following output: 
![image](https://user-images.githubusercontent.com/56845330/96790344-8d60af00-13ee-11eb-9dcd-09b629fe4575.png)

I do see the 'XDG_RUNTIME_DIR not set in environment' error however havve done a large amount of searching that yielded no working result.
How may I fix this?
Again, apologies for the questions that are most likely easy to fix.

**Comment by hrmckay** [comment]
WSL on Windows 10 does not support graphics.  Microsoft says it is coming "soon" but it is not available now.  The wasp-os simulator opens a graphics window and WSL cannot handle that.  I found that I had to run Debian Linux under an emulator in order to get the simulator to work.

Hugh

**Comment by SC-Teuton** [comment]
> WSL on Windows 10 does not support graphics. Microsoft says it is coming "soon" but it is not available now. The wasp-os simulator opens a graphics window and WSL cannot handle that. I found that I had to run Debian Linux under an emulator in order to get the simulator to work.
> 
> Hugh

Hi, Hugh.

Thank you for the response, though that is a shame to hear.
Are there any resources out there that you can offer on running a Debian Emulator, please?

And I assume that means it's still possible to actually compile and flash code to the PineTime (using the Android app or cables in the dev kit) despite this? I have mine currently being shipped to me so I'm unable to test it on my own watch just yet.

Cheers~

**Comment by hrmckay** [comment]
I run Debian under an emulator called Parallels on a MacBook Pro.  For a PC running Windows there are several emulators, QEMU and VirtualBox are two of the better known ones.

From your previous screen shot it looks like only the "make sim" command failed.  The other commands would have created the necessary files for the watch, like micropython.zip.  I copy these files to my Android phone using DropBox and then use the Nordic nRF Connect app to send the files to the watch.  As I understand it the current production PineTime, not the dev kit, has a bootloader incompatible with wasp-os but Daniel has instructions on fixing this.

Hugh

**Comment by SC-Teuton** [comment]
> I run Debian under an emulator called Parallels on a MacBook Pro. For a PC running Windows there are several emulators, QEMU and VirtualBox are two of the better known ones.
> 
> From your previous screen shot it looks like only the "make sim" command failed. The other commands would have created the necessary files for the watch, like micropython.zip. I copy these files to my Android phone using DropBox and then use the Nordic nRF Connect app to send the files to the watch. As I understand it the current production PineTime, not the dev kit, has a bootloader incompatible with wasp-os but Daniel has instructions on fixing this.
> 
> Hugh


Excellent, thank you, I'll go ahead with that!

Yes, from what I have done, "make sim" was the only command that has failed. The others before worked fine. I am getting the dev kit, so hopefully it shouldn't be a problem, and I have seen Daniel's video on the topic of flashing the files to the watch with the app.

Thank you for your help!
