### ISSUE TITLE
Using wasp-os with IoT devices

### ISSUE THREAD

**Issue by JustAnotherMaker** [daniel-thompson/wasp-os#86]
I was wondering if it would be possible to use this for IOT devices to make for easier integration between devices such as the pinephone and pinetime and IOT device

**Comment by daniel-thompson** [comment]
I'm not entirely sure what you mean here.

If you are looking for a "hub" for sensors then using the PinePhone as the hub is probably easier than using PineTime for that. Either way it might be better to discuss this sort of thing on the Pine64 forums: https://forum.pine64.org/forumdisplay.php?fid=134
